FROM node:14.14.0-alpine as builder
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nignx/conf.d/default.conf
COPY --from=builder /app/build usr/share/nginx/html